
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const Account = lazy(() => import("./pages/Account.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const CreateTest = lazy(() => import("./pages/CreateTest.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const ManageQuestions = lazy(() => import("./pages/ManageQuestions.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/account", element: <UserGuard><Account /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/create-test", element: <UserGuard><CreateTest /></UserGuard>},
	{ path: "/createtest", element: <UserGuard><CreateTest /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/manage-questions", element: <UserGuard><ManageQuestions /></UserGuard>},
	{ path: "/managequestions", element: <UserGuard><ManageQuestions /></UserGuard>},

];
